---
# Automations for COVID data
########
covid_automation:
  input_text:
    postcode:
      initial: !secret postcode
  automation:
    - id: '1611945742569'
      alias: COVID Alert
      description: Send notification if COVID rate or alert level changes.
      trigger:
        - platform: state
          entity_id: sensor.covid_alert_level
        - platform: state
          entity_id: sensor.covid_rate
      condition:
        - condition: time
          after: 06:00:00
          before: '23:00:00'
        - condition: numeric_state
          entity_id: sensor.covid_rate
          above: 0
      action:
        - service: notify.adult_phones
          data:
            title: COVID Alert
            message: >
              {% if not states('sensor.covid_alert_raw') == 'unknown' -%}
              {{ state_attr('sensor.covid_alert_raw', 'name') }}, {% endif %}
              {{- states('sensor.covid_rate') }}/100k people.
            data:
              clickAction: "https://coronavirus.data.gov.uk/search?postcode=\
                {{- states('input_text.postcode') | replace(' ', '+') -}}"
              channel: Alerts
      mode: single
...
