---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Include customizations automatically
homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_merge_named packages

# Text to speech
tts:
  - platform: google_translate

recorder:
  purge_keep_days: 730
  commit_interval: 30
  exclude:
    entities:
      - sensor.hp_envy_photo_7100_series_uptime
      - sensor.current

input_text:
  hostname:
    initial: !env_var HOSTNAME

history:
  exclude:
    domains:
      - automation
      - updater
    entities:
      - binary_sensor.updater

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

#media_player: !include players.yaml

ifttt:
  key: !secret ifttt_key

discovery:

rest_command:
  voice_monkey:
    url: https://api.voicemonkey.io/trigger
    method: POST
    verify_ssl: true
    content_type: 'application/json'
    payload: !secret voice_monkey_template
...
