---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Include customizations automatically
homeassistant:
  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

media_player: !include players.yaml

ifttt:
  key: !secret ifttt_key

mqtt:
  broker: 127.0.0.1

discovery:

sensor: !include_dir_merge_list sensors/

rest_command:
  voice_monkey:
    url: https://api.voicemonkey.io/trigger
    method: POST
    verify_ssl: true
    content_type: 'application/json'
    payload: !secret voice_monkey_template
...
