---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Include customizations automatically
homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_merge_named packages

# Text to speech
tts:
  - platform: google_translate

recorder:
  purge_keep_days: 180
  commit_interval: 30
  exclude:
    entities:
      - sensor.hp_envy_photo_7100_series_uptime
      - sensor.current

input_text:
  hostname:
    initial: !env_var HOSTNAME

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# media_player: !include players.yaml

device_tracker:
  - platform: google_maps
    username: !secret gmail

notify:
  - name: ADULT_PHONES
    platform: group
    services:
      - service: mobile_app_pixel_6
...
