#        -g "multicast dns register = no"
#        -g "mdns name = mdns"
---
version: '2.3'
services:
  samba:
    container_name: samba
    image: dperson/samba
    command: |-
        -g "netbios name = ${HOSTNAME}"
        -g "ntlm auth = true"
        -g "security = user"
        -s "homeassistant;/share/homeassistant;yes;no;no"
        -u "pi;${SAMBAPASSWORD}"
    environment:
      - GROUPID=1000
      - HOSTNAME=${HOSTNAME}
#      - NMBD=true
      - TZ=Europe/London
      - USERID=1000
      - WORKGROUP=WORKGROUP
    healthcheck:
      disable: true
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      - /home/pi/homeassistant:/share/homeassistant
    restart: always
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    profiles:
      - mqtt
    healthcheck:
      disable: true
    ports:
      - "1883:1883"
    volumes:
      - "/home/pi/homeassistant/mosquitto/mosquitto.conf:\
        /mosquitto/config/mosquitto.conf"
      - /home/pi/homeassistant/mosquitto/data:/mosquitto/data
      - /home/pi/homeassistant/mosquitto/log:/mosquitto/log
    restart: always
  wsdd:
    container_name: wsdd
    image: kosdk/wsdd
    environment:
      - HOST_NAME=${HOSTNAME}
    healthcheck:
      disable: true
    network_mode: host
    restart: always
  homeassistant:
    container_name: hassio
    image: "ghcr.io/home-assistant/home-assistant:stable"
    healthcheck:
      disable: true
    volumes:
      - /home/pi/homeassistant/config:/config
      - /home/pi/homeassistant/scripts:/home/homeassistant/scripts:ro
      - /etc/localtime:/etc/localtime:ro
      - /media/pi/MEDIA:/media
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    restart: always
    network_mode: host
  esphome:
    profiles:
      - dev
    container_name: esphome
    image: jringe/esphome
    volumes:
      - /home/pi/homeassistant/esphome:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    restart: always
    privileged: true
    network_mode: host
networks:
  default:
    external: true
    name: mqtt-net
...
