---
# Miscellaneous sensors
########

- platform: uptime
- platform: version
  source: local
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, make sure configuration file is encoded as UTF-8
  unit_of_measurement: "°C"
  scan_interval: 60
  value_template: "{{ value | multiply(0.001) | round(1) }}"
- platform: template
  sensors:
    sunrise:
      friendly_name: "Sunrise"
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_rising'))
        | timestamp_custom ('%H:%M') }}
      icon_template: 'mdi:weather-sunset-up'
    sunset:
      friendly_name: "Sunset"
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_setting'))
        | timestamp_custom ('%H:%M') }}
      icon_template: 'mdi:weather-sunset-down'
- platform: mqtt
  name: "Smartbell status"
  state_topic: 'smartbell/smartbell1/status'
  icon: 'mdi:doorbell'
- platform: mqtt
  name: "RTL-SDR status"
  state_topic: 'rtl_433/status'
  icon: 'mdi:antenna'
...
