---
# Miscellaneous sensors
########

- platform: uptime
- platform: version
  source: local
- platform: template
  sensors:
    sunrise:
      friendly_name: "Sunrise"
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_rising'))
        | timestamp_custom ('%H:%M') }}
      icon_template: 'mdi:weather-sunset-up'
    sunset:
      friendly_name: "Sunset"
      value_template: >
        {{ as_timestamp(state_attr('sun.sun', 'next_setting'))
        | timestamp_custom ('%H:%M') }}
      icon_template: 'mdi:weather-sunset-down'
...
