---
# Recycling info sensors
########

- platform: command_line
  command: >
    /home/homeassistant/scripts/fetch_bin_collections.py
    `/home/homeassistant/scripts/hass_secret bristol_uprn`
  name: 'Bin Day'
  json_attributes:
    - bins
    - status
  scan_interval: 84000
  value_template: '{{ value_json }}'
- platform: template
  sensors:
    green_bin_day:
      icon_template: 'mdi:trash-can-outline'
      friendly_name: 'Green bin'
      value_template: >
        {% set next_day =
               state_attr('sensor.bin_day', 'bins')['Green']['next_date'] -%}
        {% set last_day =
               state_attr('sensor.bin_day', 'bins')['Green']['last_date'] -%}
        {% set days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
                      'Friday', 'Saturday', 'Sunday'] -%}
        {% set months = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                         'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] -%}
        {% set next_dt = strptime(next_day, "%Y-%m-%d") -%}
        {% if now() | as_timestamp - last_day | as_timestamp < 86400
           or next_day | as_timestamp - now() | as_timestamp < 0 -%}
          Today
        {%- elif next_day | as_timestamp - now() | as_timestamp < 86400 -%}
          Tomorrow
        {%- elif next_day | as_timestamp - now() | as_timestamp < 518400 -%}
          {{ days[next_dt.weekday()] }}
        {%- else -%}
          {{ days[next_dt.weekday()][:2] }}
          {{ next_dt.day }}
          {{ months[next_dt.month] }}
        {%- endif %}
    black_bin_day:
      icon_template: 'mdi:trash-can-outline'
      friendly_name: 'Black bin'
      value_template: >
        {% set next_day =
               state_attr('sensor.bin_day', 'bins')['Black']['next_date'] -%}
        {% set last_day =
               state_attr('sensor.bin_day', 'bins')['Black']['last_date'] -%}
        {% set days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
                      'Friday', 'Saturday', 'Sunday'] -%}
        {% set months = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                         'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] -%}
        {% set next_dt = strptime(next_day, "%Y-%m-%d") -%}
        {% if now() | as_timestamp - last_day | as_timestamp < 86400
           or next_day | as_timestamp - now() | as_timestamp < 0 -%}
          Today
        {%- elif next_day | as_timestamp - now() | as_timestamp < 86400 -%}
          Tomorrow
        {%- elif next_day | as_timestamp - now() | as_timestamp < 518400 -%}
          {{ days[next_dt.weekday()] }}
        {%- else -%}
          {{ days[next_dt.weekday()][:2] }}
          {{ next_dt.day }}
          {{ months[next_dt.month] }}
        {%- endif %}
...
