---
# Notify when a new Home Assistant version is available
###

- alias: "Update Available Notification"
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: "off"
      to: "on"
  action:
    - service: persistent_notification.create
      data:
        message: >
          **Home Assistant
          {{ state_attr('binary_sensor.updater', 'newest_version') }}
          is available.**


          See [Release Notes](
          {{ state_attr('binary_sensor.updater', 'release_notes') }}
          ) and [Update Instructions](
          https://www.home-assistant.io/common-tasks/core/).
...
