#!/bin/bash
#
# Get COVID alert for local authority area (LTLA) as JSON.
# Returns JSON formatted numeric level, name, date and description URL.
#
# Service info at https://coronavirus.data.gov.uk/details/developers-guide
#

if [[ $# -eq 0 ]] ; then
    echo 'fetch_covid_alert LTLA'
    exit 0
fi

wget -qO- "https://api.coronavirus.data.gov.uk/v2/data?areaType=ltla&areaCode=$1&metric=alertLevel&format=json" \
  | jq ".body \
    | sort_by(.date) \
    | last \
    | {level: .alertLevel, name: .alertLevelName, url: .alertLevelUrl, date}"
