#!/bin/bash
#
# Return a secret from Home Assistant's secrets.yaml file
#

if [[ $# -eq 0 ]] ; then
    echo 'Usage: hass_secret secret_key'
    exit 0
fi

cat /config/secrets.yaml \
  | grep ^$1: \
  | grep -oP '(?<=:).*' \
  | sed 's/^ *//g'
