---
# Automations for recycling sensors
########

recycling_automation:
  automation:
    - id: '1611943017008'
      alias: Bin day notification
      description: >
        Send a notification when it is Green Bin Day or Black Bin Day.
      trigger:
        - platform: time
          at: 06:00:00
      condition:
        - condition: not
          conditions:
            - condition: state
              entity_id: input_select.energy_schedule
              state: Away
        - condition: or
          conditions:
            - condition: state
              entity_id: sensor.black_bin
              state: Today
            - condition: state
              entity_id: sensor.green_bin
              state: Today
      action:
        - service: notify.adult_phones
          data:
            title: Bin day
            message: |
              {% set colour = 'Black' -%}
              {% if is_state('sensor.green_bin', 'Today') -%}
                {% set colour = 'Green' %}
              {%- endif -%} {{ colour }} Bin Day
            data:
              clickAction: noAction
              channel: Recycling
      mode: single
...
